2022-02-01 12:30:34,054 INFO: Initialized curve data.
2022-02-01 12:30:34,059 INFO: Setting up initial twist data...
2022-02-01 12:30:35,345 INFO: Twist setup complete.
2022-02-01 12:30:35,346 INFO: Searching for rational points on each twist...
2022-02-01 12:30:37,305 INFO: Finished searching for rational points on each twist.
2022-02-01 12:30:37,306 INFO: Testing local solvability of twists...
2022-02-01 12:30:42,089 INFO: Finished local solvability testing.
2022-02-01 12:30:42,090 INFO: Computing elliptic curve a-invariants...
2022-02-01 12:30:55,081 INFO: Finished computation of a-invariants.
2022-02-01 12:30:55,082 INFO: Computing MW group (delta = ['2', '2', '10', '-3/2', '-3', '-1/2'], g = [-4, -3, -18, 3, 6, 1])...
2022-02-01 12:34:28,632 INFO: Finished MW computation (delta = ['2', '2', '10', '-3/2', '-3', '-1/2'], g = [-4, -3, -18, 3, 6, 1])
2022-02-01 12:34:28,635 INFO: Computing MW group (delta = ['-4', '-4', '-18', '3', '6', '1'], g = [-4, -3, -18, 3, 6, 1])...
2022-02-01 12:39:41,401 INFO: Finished MW computation (delta = ['-4', '-4', '-18', '3', '6', '1'], g = [-4, -3, -18, 3, 6, 1])
2022-02-01 12:39:41,404 INFO: Computing MW group (delta = ['1'], g = [-4, -3, -18, 3, 6, 1])...
2022-02-01 15:00:39,959 ERROR: An exception occurred. Recording data and exiting.
Traceback (most recent call last):
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 514, in <module>
    rank, MW_proven, orders, gens = twist_MW_group(D)
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 329, in twist_MW_group
    A, mw, bool_rank, bool_index = magma.MordellWeilGroup(E, nvals=_sage_const_4 )
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1787, in __call__
    return M.function_call(self._name,
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1162, in function_call
    return self._do_call(fun, nvals)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1221, in _do_call
    raise TypeError("Error executing Magma code:\n%s" % out)
TypeError: Error executing Magma code:

Current total memory usage: 16355.3MB, failed memory request: 32.0MB
System Error: User memory limit has been reached
2022-02-02 04:48:11,089 INFO: Loaded curve data from file.
2022-02-02 04:48:11,090 INFO: Reducing MW generators...
2022-02-02 04:48:12,146 INFO: Finished reducing MW generators.
2022-02-02 04:48:12,148 INFO: Skipped Chabauty because MW group hasn't been provably computed. (delta = ['2', '2', '10', '-3/2', '-3', '-1/2'], g = [-4, -3, -18, 3, 6, 1])
2022-02-02 04:48:12,148 INFO: Running elliptic Chabauty (delta = ['-4', '-4', '-18', '3', '6', '1'], g = [-4, -3, -18, 3, 6, 1])...
