2022-02-01 12:30:22,217 INFO: Initialized curve data.
2022-02-01 12:30:22,226 INFO: Setting up initial twist data...
2022-02-01 12:30:23,447 INFO: Twist setup complete.
2022-02-01 12:30:23,447 INFO: Searching for rational points on each twist...
2022-02-01 12:30:26,255 INFO: Finished searching for rational points on each twist.
2022-02-01 12:30:26,255 INFO: Testing local solvability of twists...
2022-02-01 14:07:16,971 ERROR: An exception occurred. Recording data and exiting.
Traceback (most recent call last):
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 472, in <module>
    loc_solv = twists_locally_solvable(curve, twist_index=i)
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 241, in twists_locally_solvable
    ls = magma.function_call("is_genus5_locally_solvable", [Z, bad_primes], {"Skip": [_sage_const_2 ]})
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1162, in function_call
    return self._do_call(fun, nvals)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1212, in _do_call
    return self(code)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 791, in __call__
    A = Expect.__call__(self, x)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/interface.py", line 295, in __call__
    return cls(self, x, name=name)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/expect.py", line 1468, in __init__
    self._name = parent._create(value, name=name)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/interface.py", line 500, in _create
    self.set(name, value)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 628, in set
    raise TypeError("Error executing Magma code:\n%s" % out)
TypeError: Error executing Magma code:

Current total memory usage: 16356.7MB, failed memory request: 32.0MB
System Error: User memory limit has been reached
2022-02-02 04:42:40,099 INFO: Loaded curve data from file.
2022-02-02 04:42:40,100 INFO: Reducing MW generators...
2022-02-02 04:42:40,100 INFO: Finished reducing MW generators.
2022-02-02 04:42:40,103 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['-16', '6', '11', '9', '-7', '1'], g = [-17, 7, 11, 9, -7, 1])
2022-02-02 04:42:40,103 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['4', '-11/2', '1'], g = [-17, 7, 11, 9, -7, 1])
2022-02-02 04:42:40,103 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['1'], g = [-17, 7, 11, 9, -7, 1])
2022-02-02 04:42:40,103 INFO: Skipped Chabauty because no base point (delta = ['25/2', '-13', '1', '-11/2', '7/2', '-1/2'])
2022-02-02 04:42:40,105 INFO: Tasks complete. Recording data and exiting.
2022-02-12 17:14:22,459 INFO: Loaded curve data from file.
2022-02-12 17:14:22,459 INFO: Tasks complete. Recording data and exiting.
