2022-02-01 12:30:24,482 INFO: Initialized curve data.
2022-02-01 12:30:24,486 INFO: Setting up initial twist data...
2022-02-01 12:30:25,459 INFO: Twist setup complete.
2022-02-01 12:30:25,459 INFO: Searching for rational points on each twist...
2022-02-01 12:30:27,547 INFO: Finished searching for rational points on each twist.
2022-02-01 12:30:27,547 INFO: Testing local solvability of twists...
2022-02-01 12:51:49,006 ERROR: An exception occurred. Recording data and exiting.
Traceback (most recent call last):
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 472, in <module>
    loc_solv = twists_locally_solvable(curve, twist_index=i)
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 245, in twists_locally_solvable
    ls2 = magma.function_call("is_genus5_locally_solvable_at_2", Z)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1162, in function_call
    return self._do_call(fun, nvals)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1212, in _do_call
    return self(code)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 791, in __call__
    A = Expect.__call__(self, x)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/interface.py", line 295, in __call__
    return cls(self, x, name=name)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/expect.py", line 1468, in __init__
    self._name = parent._create(value, name=name)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/interface.py", line 500, in _create
    self.set(name, value)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 628, in set
    raise TypeError("Error executing Magma code:\n%s" % out)
TypeError: Error executing Magma code:

Current total memory usage: 16354.1MB, failed memory request: 32.0MB
System Error: User memory limit has been reached
2022-02-02 08:25:40,339 INFO: Loaded curve data from file.
2022-02-02 08:25:40,339 INFO: Reducing MW generators...
2022-02-02 08:25:40,339 INFO: Finished reducing MW generators.
2022-02-02 08:25:40,340 INFO: Skipped Chabauty because no base point (delta = ['-5/2', '1/2', '5/2', '-3/2', '3/2', '1/2'])
2022-02-02 08:25:40,340 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['1'], g = [-8, -4, 5, -1, 3, 1])
2022-02-02 08:25:40,340 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['-9', '-5', '5', '-1', '3', '1'], g = [-8, -4, 5, -1, 3, 1])
2022-02-02 08:25:40,340 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['-3/2', '-1', '1'], g = [-8, -4, 5, -1, 3, 1])
2022-02-02 08:25:40,341 INFO: Tasks complete. Recording data and exiting.
