2022-01-11 15:10:12,723 INFO: Initialized curve data.
2022-01-11 15:10:12,724 INFO: Setting up initial twist data...
2022-01-11 15:10:14,005 INFO: Twist setup complete.
2022-01-11 15:10:14,006 INFO: Searching for rational points on each twist...
2022-01-11 15:10:15,568 INFO: Finished searching for rational points on each twist.
2022-01-11 15:10:15,568 INFO: Testing local solvability of twists...
2022-01-11 15:30:43,450 ERROR: An exception occurred. Recording data and exiting.
Traceback (most recent call last):
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 464, in <module>
    loc_solv = twists_locally_solvable(curve, twist_index=i)
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 245, in twists_locally_solvable
    ls2 = magma.function_call("is_genus5_locally_solvable_at_2", Z)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1162, in function_call
    return self._do_call(fun, nvals)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1212, in _do_call
    return self(code)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 791, in __call__
    A = Expect.__call__(self, x)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/interface.py", line 295, in __call__
    return cls(self, x, name=name)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/expect.py", line 1468, in __init__
    self._name = parent._create(value, name=name)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/interface.py", line 500, in _create
    self.set(name, value)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 628, in set
    raise TypeError("Error executing Magma code:\n%s" % out)
TypeError: Error executing Magma code:

Current total memory usage: 16354.1MB, failed memory request: 32.0MB
System Error: User memory limit has been reached
2022-01-14 09:07:22,720 INFO: Loaded curve data from file.
2022-01-14 09:07:22,720 INFO: Reducing MW generators...
2022-01-14 09:07:22,720 INFO: Finished reducing MW generators.
2022-01-14 09:07:22,723 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['1'], g = [11, 11, -13, 1, 5, 1])
2022-01-14 09:07:22,723 INFO: Skipped Chabauty because no base point (delta = ['-7', '-4', '15/2', '-3/2', '-5/2', '-1/2'])
2022-01-14 09:07:22,723 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['-3/2', '0', '1'], g = [11, 11, -13, 1, 5, 1])
2022-01-14 09:07:22,723 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['12', '10', '-13', '1', '5', '1'], g = [11, 11, -13, 1, 5, 1])
2022-01-14 09:07:22,724 INFO: Tasks complete. Recording data and exiting.
