2022-01-13 21:54:35,137 INFO: Initialized curve data.
2022-01-13 21:54:35,140 INFO: Setting up initial twist data...
2022-01-13 21:54:36,244 INFO: Twist setup complete.
2022-01-13 21:54:36,244 INFO: Searching for rational points on each twist...
2022-01-13 21:54:38,608 INFO: Finished searching for rational points on each twist.
2022-01-13 21:54:38,609 INFO: Testing local solvability of twists...
2022-01-13 21:54:38,614 INFO: Finished local solvability testing.
2022-01-13 21:54:38,615 INFO: Computing elliptic curve a-invariants...
2022-01-13 21:54:45,904 INFO: Finished computation of a-invariants.
2022-01-13 21:54:45,905 INFO: Computing MW group (delta = ['1', '-1'], g = [4, 16, 0, -43, 20, 4])...
2022-01-13 21:57:48,670 INFO: Finished MW computation (delta = ['1', '-1'], g = [4, 16, 0, -43, 20, 4])
2022-01-13 21:57:48,674 INFO: Computing MW group (delta = ['4', '15', '1', '-43', '20', '4'], g = [4, 16, 0, -43, 20, 4])...
2022-01-13 22:04:58,637 INFO: Finished MW computation (delta = ['4', '15', '1', '-43', '20', '4'], g = [4, 16, 0, -43, 20, 4])
2022-01-13 22:04:58,640 INFO: Computing MW group (delta = ['1'], g = [4, 16, 0, -43, 20, 4])...
2022-01-13 23:52:03,765 ERROR: An exception occurred. Recording data and exiting.
Traceback (most recent call last):
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 506, in <module>
    rank, MW_proven, orders, gens = twist_MW_group(D)
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 329, in twist_MW_group
    A, mw, bool_rank, bool_index = magma.MordellWeilGroup(E, nvals=_sage_const_4 )
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1787, in __call__
    return M.function_call(self._name,
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1162, in function_call
    return self._do_call(fun, nvals)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1221, in _do_call
    raise TypeError("Error executing Magma code:\n%s" % out)
TypeError: Error executing Magma code:

Current total memory usage: 16198.2MB, failed memory request: 2530.1MB
System Error: User memory limit has been reached
