2022-01-11 15:30:24,800 INFO: Initialized curve data.
2022-01-11 15:30:24,808 INFO: Setting up initial twist data...
2022-01-11 15:30:25,797 INFO: Twist setup complete.
2022-01-11 15:30:25,797 INFO: Searching for rational points on each twist...
2022-01-11 15:30:27,597 INFO: Finished searching for rational points on each twist.
2022-01-11 15:30:27,597 INFO: Testing local solvability of twists...
2022-01-11 16:40:16,515 ERROR: An exception occurred. Recording data and exiting.
Traceback (most recent call last):
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 464, in <module>
    loc_solv = twists_locally_solvable(curve, twist_index=i)
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 241, in twists_locally_solvable
    ls = magma.function_call("is_genus5_locally_solvable", [Z, bad_primes], {"Skip": [_sage_const_2 ]})
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1162, in function_call
    return self._do_call(fun, nvals)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1212, in _do_call
    return self(code)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 791, in __call__
    A = Expect.__call__(self, x)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/interface.py", line 295, in __call__
    return cls(self, x, name=name)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/expect.py", line 1468, in __init__
    self._name = parent._create(value, name=name)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/interface.py", line 500, in _create
    self.set(name, value)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 628, in set
    raise TypeError("Error executing Magma code:\n%s" % out)
TypeError: Error executing Magma code:

Current total memory usage: 16356.7MB, failed memory request: 32.0MB
System Error: User memory limit has been reached
2022-01-14 09:07:55,246 INFO: Loaded curve data from file.
2022-01-14 09:07:55,246 INFO: Reducing MW generators...
2022-01-14 09:07:55,246 INFO: Finished reducing MW generators.
2022-01-14 09:07:55,249 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['9', '-21', '-17', '3', '5', '1'], g = [8, -20, -17, 3, 5, 1])
2022-01-14 09:07:55,249 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['1'], g = [8, -20, -17, 3, 5, 1])
2022-01-14 09:07:55,249 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['-3/2', '3', '1'], g = [8, -20, -17, 3, 5, 1])
2022-01-14 09:07:55,249 INFO: Skipped Chabauty because no base point (delta = ['37/2', '-91/2', '-89/2', '13/2', '25/2', '5/2'])
2022-01-14 09:07:55,254 INFO: Tasks complete. Recording data and exiting.
