2022-02-01 12:30:08,470 INFO: Initialized curve data.
2022-02-01 12:30:08,494 INFO: Setting up initial twist data...
2022-02-01 12:30:10,196 INFO: Twist setup complete.
2022-02-01 12:30:10,196 INFO: Searching for rational points on each twist...
2022-02-01 12:30:14,300 INFO: Finished searching for rational points on each twist.
2022-02-01 12:30:14,300 INFO: Testing local solvability of twists...
2022-02-01 12:54:33,876 ERROR: An exception occurred. Recording data and exiting.
Traceback (most recent call last):
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 472, in <module>
    loc_solv = twists_locally_solvable(curve, twist_index=i)
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 245, in twists_locally_solvable
    ls2 = magma.function_call("is_genus5_locally_solvable_at_2", Z)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1162, in function_call
    return self._do_call(fun, nvals)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1212, in _do_call
    return self(code)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 791, in __call__
    A = Expect.__call__(self, x)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/interface.py", line 295, in __call__
    return cls(self, x, name=name)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/expect.py", line 1468, in __init__
    self._name = parent._create(value, name=name)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/interface.py", line 500, in _create
    self.set(name, value)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 628, in set
    raise TypeError("Error executing Magma code:\n%s" % out)
TypeError: Error executing Magma code:

Current total memory usage: 16373.8MB, failed memory request: 32.0MB
System Error: User memory limit has been reached
2022-02-02 04:42:40,919 INFO: Loaded curve data from file.
2022-02-02 04:42:40,929 INFO: Reducing MW generators...
2022-02-02 04:42:40,929 INFO: Finished reducing MW generators.
2022-02-02 04:42:40,931 INFO: Skipped Chabauty because no base point (delta = ['8', '2', '-21', '-7', '7'])
2022-02-02 04:42:40,931 INFO: Skipped Chabauty because no base point (delta = ['0', '17', '-7', '-34', '1', '7'])
2022-02-02 04:42:40,931 INFO: Skipped Chabauty because no base point (delta = ['5', '-9', '-27/2', '39/2', '23/2', '-7'])
2022-02-02 04:42:40,931 INFO: Skipped Chabauty because no base point (delta = ['9/2', '-9', '-8', '31/2', '9/2', '-7/2'])
2022-02-02 04:42:40,931 INFO: Skipped Chabauty because no base point (delta = ['-1/2', '0', '1'])
2022-02-02 04:42:40,931 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['1'], g = [-1, 1, 1])
2022-02-02 04:42:40,931 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['1'], g = [9, -8, -14, 7])
2022-02-02 04:42:40,931 INFO: Skipped Chabauty because no base point (delta = ['9/7', '-9/14', '-127/14', '4', '163/14', '-3/2'])
2022-02-02 04:42:40,932 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['9', '-16', '-14', '29', '7', '-7'], g = [-1, 1, 1])
2022-02-02 04:42:40,932 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['9', '-16', '-14', '29', '7', '-7'], g = [9, -8, -14, 7])
2022-02-02 04:42:40,933 INFO: Tasks complete. Recording data and exiting.
2022-02-12 17:29:53,727 INFO: Loaded curve data from file.
2022-02-12 17:29:53,727 INFO: Tasks complete. Recording data and exiting.
