2022-01-13 21:54:35,725 INFO: Initialized curve data.
2022-01-13 21:54:35,728 INFO: Setting up initial twist data...
2022-01-13 21:54:36,848 INFO: Twist setup complete.
2022-01-13 21:54:36,848 INFO: Searching for rational points on each twist...
2022-01-13 21:54:38,980 INFO: Finished searching for rational points on each twist.
2022-01-13 21:54:38,980 INFO: Testing local solvability of twists...
2022-01-13 22:13:53,748 ERROR: An exception occurred. Recording data and exiting.
Traceback (most recent call last):
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 464, in <module>
    loc_solv = twists_locally_solvable(curve, twist_index=i)
  File "/project/arithgeo/drhast/twocover-descent/./twocover-processor.sage.py", line 245, in twists_locally_solvable
    ls2 = magma.function_call("is_genus5_locally_solvable_at_2", Z)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1162, in function_call
    return self._do_call(fun, nvals)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 1212, in _do_call
    return self(code)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 791, in __call__
    A = Expect.__call__(self, x)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/interface.py", line 295, in __call__
    return cls(self, x, name=name)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/expect.py", line 1468, in __init__
    self._name = parent._create(value, name=name)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/interface.py", line 500, in _create
    self.set(name, value)
  File "/share/pkg.7/sagemath/9.3/install/lib/python3.9/site-packages/sage/interfaces/magma.py", line 628, in set
    raise TypeError("Error executing Magma code:\n%s" % out)
TypeError: Error executing Magma code:

Current total memory usage: 16352.5MB, failed memory request: 32.0MB
System Error: User memory limit has been reached
2022-01-14 11:35:10,006 INFO: Loaded curve data from file.
2022-01-14 11:35:10,006 INFO: Reducing MW generators...
2022-01-14 11:35:10,006 INFO: Finished reducing MW generators.
2022-01-14 11:35:10,008 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['-4', '14', '-1', '-19', '1', '1'], g = [-5, 15, -1, -19, 1, 1])
2022-01-14 11:35:10,009 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['3', '-9', '3/2', '19/2', '-1/2', '-1/2'], g = [-5, 15, -1, -19, 1, 1])
2022-01-14 11:35:10,009 INFO: Skipped Chabauty because MW generators haven't been computed. (delta = ['1'], g = [-5, 15, -1, -19, 1, 1])
2022-01-14 11:35:10,009 INFO: Skipped Chabauty because no base point (delta = ['1/2', '-1'])
2022-01-14 11:35:10,010 INFO: Tasks complete. Recording data and exiting.
